// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/matching_engine.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Order types
type OrderType int32

const (
	OrderType_MARKET OrderType = 0
	OrderType_LIMIT  OrderType = 1
)

// Enum value maps for OrderType.
var (
	OrderType_name = map[int32]string{
		0: "MARKET",
		1: "LIMIT",
	}
	OrderType_value = map[string]int32{
		"MARKET": 0,
		"LIMIT":  1,
	}
)

func (x OrderType) Enum() *OrderType {
	p := new(OrderType)
	*p = x
	return p
}

func (x OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_engine_proto_enumTypes[0].Descriptor()
}

func (OrderType) Type() protoreflect.EnumType {
	return &file_proto_matching_engine_proto_enumTypes[0]
}

func (x OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderType.Descriptor instead.
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

// Order side
type OrderSide int32

const (
	OrderSide_BUY  OrderSide = 0
	OrderSide_SELL OrderSide = 1
)

// Enum value maps for OrderSide.
var (
	OrderSide_name = map[int32]string{
		0: "BUY",
		1: "SELL",
	}
	OrderSide_value = map[string]int32{
		"BUY":  0,
		"SELL": 1,
	}
)

func (x OrderSide) Enum() *OrderSide {
	p := new(OrderSide)
	*p = x
	return p
}

func (x OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_matching_engine_proto_enumTypes[1].Descriptor()
}

func (OrderSide) Type() protoreflect.EnumType {
	return &file_proto_matching_engine_proto_enumTypes[1]
}

func (x OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderSide.Descriptor instead.
func (OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{1}
}

// PlaceOrderRequest contains order details
type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContractId    string                 `protobuf:"bytes,3,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Type          OrderType              `protobuf:"varint,4,opt,name=type,proto3,enum=matching.OrderType" json:"type,omitempty"`
	Side          OrderSide              `protobuf:"varint,5,opt,name=side,proto3,enum=matching.OrderSide" json:"side,omitempty"`
	Quantity      int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	LimitPrice    float64                `protobuf:"fixed64,7,opt,name=limit_price,json=limitPrice,proto3" json:"limit_price,omitempty"` // Optional, only for LIMIT orders
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_proto_matching_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{0}
}

func (x *PlaceOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceOrderRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_MARKET
}

func (x *PlaceOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_BUY
}

func (x *PlaceOrderRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PlaceOrderRequest) GetLimitPrice() float64 {
	if x != nil {
		return x.LimitPrice
	}
	return 0
}

// PlaceOrderResponse contains the result of order placement
type PlaceOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "ACTIVE", "FILLED", "PARTIALLY_FILLED"
	QuantityFilled int32                  `protobuf:"varint,3,opt,name=quantity_filled,json=quantityFilled,proto3" json:"quantity_filled,omitempty"`
	AveragePrice   float64                `protobuf:"fixed64,4,opt,name=average_price,json=averagePrice,proto3" json:"average_price,omitempty"`
	Trades         []*Trade               `protobuf:"bytes,5,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaceOrderResponse) Reset() {
	*x = PlaceOrderResponse{}
	mi := &file_proto_matching_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderResponse) ProtoMessage() {}

func (x *PlaceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderResponse.ProtoReflect.Descriptor instead.
func (*PlaceOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceOrderResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PlaceOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceOrderResponse) GetQuantityFilled() int32 {
	if x != nil {
		return x.QuantityFilled
	}
	return 0
}

func (x *PlaceOrderResponse) GetAveragePrice() float64 {
	if x != nil {
		return x.AveragePrice
	}
	return 0
}

func (x *PlaceOrderResponse) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

// Trade represents a matched trade
type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	MakerOrderId  string                 `protobuf:"bytes,2,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	TakerOrderId  string                 `protobuf:"bytes,3,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ExecutedAt    int64                  `protobuf:"varint,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"` // Unix timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_proto_matching_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetMakerOrderId() string {
	if x != nil {
		return x.MakerOrderId
	}
	return ""
}

func (x *Trade) GetTakerOrderId() string {
	if x != nil {
		return x.TakerOrderId
	}
	return ""
}

func (x *Trade) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Trade) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Trade) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

// CancelOrderRequest contains order cancellation details
type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ContractId    string                 `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_proto_matching_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{3}
}

func (x *CancelOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CancelOrderRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

// CancelOrderResponse contains the result of cancellation
type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_proto_matching_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{4}
}

func (x *CancelOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetOrderBookRequest requests the order book for a contract
type GetOrderBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContractId    string                 `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	Depth         int32                  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"` // Number of price levels to return
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookRequest) Reset() {
	*x = GetOrderBookRequest{}
	mi := &file_proto_matching_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookRequest) ProtoMessage() {}

func (x *GetOrderBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookRequest.ProtoReflect.Descriptor instead.
func (*GetOrderBookRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderBookRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *GetOrderBookRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

// GetOrderBookResponse contains the order book
type GetOrderBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          []*OrderBookLevel      `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*OrderBookLevel      `protobuf:"bytes,2,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderBookResponse) Reset() {
	*x = GetOrderBookResponse{}
	mi := &file_proto_matching_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderBookResponse) ProtoMessage() {}

func (x *GetOrderBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderBookResponse.ProtoReflect.Descriptor instead.
func (*GetOrderBookResponse) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderBookResponse) GetBids() []*OrderBookLevel {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *GetOrderBookResponse) GetAsks() []*OrderBookLevel {
	if x != nil {
		return x.Asks
	}
	return nil
}

// OrderBookLevel represents aggregated orders at a price level
type OrderBookLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	OrderCount    int32                  `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookLevel) Reset() {
	*x = OrderBookLevel{}
	mi := &file_proto_matching_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookLevel) ProtoMessage() {}

func (x *OrderBookLevel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookLevel.ProtoReflect.Descriptor instead.
func (*OrderBookLevel) Descriptor() ([]byte, []int) {
	return file_proto_matching_engine_proto_rawDescGZIP(), []int{7}
}

func (x *OrderBookLevel) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderBookLevel) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderBookLevel) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

var File_proto_matching_engine_proto protoreflect.FileDescriptor

const file_proto_matching_engine_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/matching_engine.proto\x12\bmatching\"\xf7\x01\n" +
	"\x11PlaceOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vcontract_id\x18\x03 \x01(\tR\n" +
	"contractId\x12'\n" +
	"\x04type\x18\x04 \x01(\x0e2\x13.matching.OrderTypeR\x04type\x12'\n" +
	"\x04side\x18\x05 \x01(\x0e2\x13.matching.OrderSideR\x04side\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vlimit_price\x18\a \x01(\x01R\n" +
	"limitPrice\"\xbe\x01\n" +
	"\x12PlaceOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12'\n" +
	"\x0fquantity_filled\x18\x03 \x01(\x05R\x0equantityFilled\x12#\n" +
	"\raverage_price\x18\x04 \x01(\x01R\faveragePrice\x12'\n" +
	"\x06trades\x18\x05 \x03(\v2\x0f.matching.TradeR\x06trades\"\xc1\x01\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12$\n" +
	"\x0emaker_order_id\x18\x02 \x01(\tR\fmakerOrderId\x12$\n" +
	"\x0etaker_order_id\x18\x03 \x01(\tR\ftakerOrderId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1f\n" +
	"\vexecuted_at\x18\x06 \x01(\x03R\n" +
	"executedAt\"P\n" +
	"\x12CancelOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\"I\n" +
	"\x13CancelOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x13GetOrderBookRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x14\n" +
	"\x05depth\x18\x02 \x01(\x05R\x05depth\"r\n" +
	"\x14GetOrderBookResponse\x12,\n" +
	"\x04bids\x18\x01 \x03(\v2\x18.matching.OrderBookLevelR\x04bids\x12,\n" +
	"\x04asks\x18\x02 \x03(\v2\x18.matching.OrderBookLevelR\x04asks\"c\n" +
	"\x0eOrderBookLevel\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1f\n" +
	"\vorder_count\x18\x03 \x01(\x05R\n" +
	"orderCount*\"\n" +
	"\tOrderType\x12\n" +
	"\n" +
	"\x06MARKET\x10\x00\x12\t\n" +
	"\x05LIMIT\x10\x01*\x1e\n" +
	"\tOrderSide\x12\a\n" +
	"\x03BUY\x10\x00\x12\b\n" +
	"\x04SELL\x10\x012\xf4\x01\n" +
	"\x0eMatchingEngine\x12G\n" +
	"\n" +
	"PlaceOrder\x12\x1b.matching.PlaceOrderRequest\x1a\x1c.matching.PlaceOrderResponse\x12J\n" +
	"\vCancelOrder\x12\x1c.matching.CancelOrderRequest\x1a\x1d.matching.CancelOrderResponse\x12M\n" +
	"\fGetOrderBook\x12\x1d.matching.GetOrderBookRequest\x1a\x1e.matching.GetOrderBookResponseB\x1bZ\x19lfg/matching-engine/protob\x06proto3"

var (
	file_proto_matching_engine_proto_rawDescOnce sync.Once
	file_proto_matching_engine_proto_rawDescData []byte
)

func file_proto_matching_engine_proto_rawDescGZIP() []byte {
	file_proto_matching_engine_proto_rawDescOnce.Do(func() {
		file_proto_matching_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_engine_proto_rawDesc), len(file_proto_matching_engine_proto_rawDesc)))
	})
	return file_proto_matching_engine_proto_rawDescData
}

var file_proto_matching_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_matching_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_matching_engine_proto_goTypes = []any{
	(OrderType)(0),               // 0: matching.OrderType
	(OrderSide)(0),               // 1: matching.OrderSide
	(*PlaceOrderRequest)(nil),    // 2: matching.PlaceOrderRequest
	(*PlaceOrderResponse)(nil),   // 3: matching.PlaceOrderResponse
	(*Trade)(nil),                // 4: matching.Trade
	(*CancelOrderRequest)(nil),   // 5: matching.CancelOrderRequest
	(*CancelOrderResponse)(nil),  // 6: matching.CancelOrderResponse
	(*GetOrderBookRequest)(nil),  // 7: matching.GetOrderBookRequest
	(*GetOrderBookResponse)(nil), // 8: matching.GetOrderBookResponse
	(*OrderBookLevel)(nil),       // 9: matching.OrderBookLevel
}
var file_proto_matching_engine_proto_depIdxs = []int32{
	0, // 0: matching.PlaceOrderRequest.type:type_name -> matching.OrderType
	1, // 1: matching.PlaceOrderRequest.side:type_name -> matching.OrderSide
	4, // 2: matching.PlaceOrderResponse.trades:type_name -> matching.Trade
	9, // 3: matching.GetOrderBookResponse.bids:type_name -> matching.OrderBookLevel
	9, // 4: matching.GetOrderBookResponse.asks:type_name -> matching.OrderBookLevel
	2, // 5: matching.MatchingEngine.PlaceOrder:input_type -> matching.PlaceOrderRequest
	5, // 6: matching.MatchingEngine.CancelOrder:input_type -> matching.CancelOrderRequest
	7, // 7: matching.MatchingEngine.GetOrderBook:input_type -> matching.GetOrderBookRequest
	3, // 8: matching.MatchingEngine.PlaceOrder:output_type -> matching.PlaceOrderResponse
	6, // 9: matching.MatchingEngine.CancelOrder:output_type -> matching.CancelOrderResponse
	8, // 10: matching.MatchingEngine.GetOrderBook:output_type -> matching.GetOrderBookResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_matching_engine_proto_init() }
func file_proto_matching_engine_proto_init() {
	if File_proto_matching_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_engine_proto_rawDesc), len(file_proto_matching_engine_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_matching_engine_proto_goTypes,
		DependencyIndexes: file_proto_matching_engine_proto_depIdxs,
		EnumInfos:         file_proto_matching_engine_proto_enumTypes,
		MessageInfos:      file_proto_matching_engine_proto_msgTypes,
	}.Build()
	File_proto_matching_engine_proto = out.File
	file_proto_matching_engine_proto_goTypes = nil
	file_proto_matching_engine_proto_depIdxs = nil
}
